"""baseline schema

Revision ID: 270b5432bd40
Revises: 
Create Date: 2026-10-02 14:51:30.111310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270b5432bd40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('accent', sa.String(length=10), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=100), nullable=True),
    sa.Column('drive_next_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('item', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('ordered', sa.Float(), nullable=True),
    sa.Column('delivered', sa.Float(), nullable=True),
    sa.Column('quantity_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_web_view_link', sa.String(length=500), nullable=True),
    sa.Column('drive_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_oauth_state',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('google_drive_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('root_folder_id', sa.String(length=100), nullable=True),
    sa.Column('shared_drive_id', sa.String(length=100), nullable=True),
    sa.Column('shared_drive_name', sa.String(length=255), nullable=True),
    sa.Column('connected_by_id', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_requests')
    op.drop_table('google_drive_account')
    op.drop_table('drive_oauth_state')
    op.drop_table('deliveries')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
