"""index deliveries by project, uploader and status

Revision ID: d5267578692f
Revises: 270b5432bd40
Create Date: 2026-10-03 16:39:56.814717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5267578692f'
down_revision = '270b5432bd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_deliveries_project_uploaded_at', ['project_id', 'uploaded_at'], unique=False)
        batch_op.create_index('ix_deliveries_status', ['status'], unique=False)
        batch_op.create_index('ix_deliveries_uploaded_by_id', ['uploaded_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_deliveries_uploaded_by_id')
        batch_op.drop_index('ix_deliveries_status')
        batch_op.drop_index('ix_deliveries_project_uploaded_at')

    # ### end Alembic commands ###
