"""bill items, bill amounts and ocr scans

Revision ID: e4a27323ee0e
Revises: d0dc350e48df
Create Date: 2026-10-10 18:01:50.307991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a27323ee0e'
down_revision = 'd0dc350e48df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_items_delivery_id'), ['delivery_id'], unique=False)

    op.create_table('ocr_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('item', sa.String(length=300), nullable=True),
    sa.Column('delivered', sa.Float(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('reading', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_scans_delivery_id'), ['delivery_id'], unique=False)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('bill_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('taxable_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('igst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###

    # Bills sent before items existed become a one-row table: their item and quantity.
    op.execute(
        "INSERT INTO delivery_items (delivery_id, position, description, quantity) "
        "SELECT id, 0, item, delivered FROM deliveries"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('total_amount')
        batch_op.drop_column('igst')
        batch_op.drop_column('sgst')
        batch_op.drop_column('cgst')
        batch_op.drop_column('taxable_amount')
        batch_op.drop_column('bill_date')
        batch_op.drop_column('invoice_number')

    with op.batch_alter_table('ocr_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_scans_delivery_id'))

    op.drop_table('ocr_scans')
    with op.batch_alter_table('delivery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_items_delivery_id'))

    op.drop_table('delivery_items')
    # ### end Alembic commands ###
