"""bill change history

Revision ID: f42778264e05
Revises: e4a27323ee0e
Create Date: 2026-10-10 18:47:13.877085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42778264e05'
down_revision = 'e4a27323ee0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('from_reading', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_changes_delivery_id'), ['delivery_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_changes_delivery_id'))

    op.drop_table('bill_changes')
    # ### end Alembic commands ###
